# wl (Broadcom 7.14.164.18) para Linux 6.12 / ARM32
#
# brcm/ = arvore brcm/arm do DD-WRT (scripts/fetch-brcm.sh)
# core/wl_core.o = nucleo binario juntado (scripts/prep-core.sh)

obj-m := wl.o

BRCM := brcm

wl-y := wl_linux.o shim.o osl_nvram.o core/wl_core.o

wl-y += $(BRCM)/shared/linux_osl.o \
	$(BRCM)/shared/siutils.o \
	$(BRCM)/shared/aiutils.o \
	$(BRCM)/shared/sbutils.o \
	$(BRCM)/shared/hndpmu.o \
	$(BRCM)/shared/hnddma.o \
	$(BRCM)/shared/bcmutils.o \
	$(BRCM)/shared/bcmsrom.o \
	$(BRCM)/shared/bcmotp.o \
	$(BRCM)/shared/nicpci.o \
	$(BRCM)/shared/pcie_core.o \
	$(BRCM)/shared/bcmevent.o \
	$(BRCM)/shared/bcmxtlv.o \
	$(BRCM)/shared/bcmwifi/src/bcmwifi_channels.o

# mesmas flags com que o nucleo foi compilado (wlconfig_lx_router_apsta
# + Makefile do kernel 4.4 do DD-WRT): os structs inline tem que bater
WLFLAGS := $(shell cat $(src)/wlflags.txt)
WLFLAGS += -DHNDCTF -DCTFPOOL -DCTFMAP -DPKTC -DCTF_PPPOE
WLFLAGS += -DBCMDRIVER -Dlinux -DDMA -DBCM47XX_CA9

ccflags-y := $(WLFLAGS) \
	-include $(src)/osl_compat.h \
	-I$(src) \
	-I$(src)/compat \
	-I$(src)/$(BRCM)/include \
	-I$(src)/$(BRCM)/common/include \
	-I$(src)/$(BRCM)/shared \
	-I$(src)/$(BRCM)/shared/bcmwifi/include \
	-I$(src)/$(BRCM)/wl/clm/include \
	-I$(src)/$(BRCM)/wl/ppr/include \
	-I$(src)/$(BRCM)/wl/dump/include \
	-I$(src)/$(BRCM)/wl/iocv/include

# codigo Broadcom antigo: silencia os avisos, mas tipos de ponteiro e
# int<->ponteiro errados sao bugs reais no 6.x (refcount_t, kernel_read...)
BRCM_OBJS := $(filter $(BRCM)/%,$(wl-y))
$(foreach o,$(BRCM_OBJS),$(eval CFLAGS_$(o) += -w))
ccflags-y += -Werror=incompatible-pointer-types -Werror=int-conversion

# o shim e quem implementa o redirecionamento de dma_sync_* (osl_compat.h)
CFLAGS_shim.o += -DWL_SHIM_NO_DMA_REDIRECT
