#!/bin/sh /etc/rc.common
# reinicia o roteador se ficar sem internet (ver /usr/sbin/netwatch)

START=99
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/netwatch
	procd_set_param respawn
	procd_close_instance
}
