#!/bin/sh /etc/rc.common
# WireGuard (wg .11) dentro de wstunnel: a rede do lab filtra o handshake do
# WireGuard. O UDP local 127.0.0.1:51820 vai por WSS ate br.rotava.com.
START=90
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/wstunnel client \
		--http-upgrade-path-prefix wstunnel \
		-L 'udp://127.0.0.1:51820:127.0.0.1:51820?timeout_sec=0' \
		wss://br.rotava.com
	procd_set_param respawn 3600 10 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
